version: "3.8"

services:
  app:
    build: .
    volumes:
      - type: bind
        source: ./data/
        target: /data/
    environment:
      CONFIG_PATH: /data/config.json
      REPORTS_PATH: /data/reports.json
    restart: always
    init: true
